{{- if and (.Values.server.ingress.webAdmin.enabled) (.Values.server.ingress.webAdmin.hostname) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-webadmin" (include "server.name" .) }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.server.ingress.webAdmin.annotations }}
    {{ toYaml .Values.server.ingress.webAdmin.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.server.ingress.webAdmin.ingressClassName }}
  ingressClassName: "{{ .Values.server.ingress.webAdmin.ingressClassName }}"
  {{- end }}
  rules:
    - host: "{{ .Values.server.ingress.webAdmin.hostname }}"
      http:
        paths:
          - path: "{{ default "/" .Values.server.ingress.webAdmin.path }}"
            pathType: "{{ default "ImplementationSpecific" .Values.server.ingress.webAdmin.pathType }}"
            backend:
              service:
                name: "{{ include "server.service.name" . }}"
                port:
                  name: webadmin
  {{- if .Values.server.ingress.webAdmin.tls }}
  tls:
    - hosts:
        - "{{ .Values.server.ingress.webAdmin.hostname }}"
      secretName: "{{ include "server.ingress.webAdmin.tls.secretName" . }}"
  {{- end }}
{{- end }}