{{- if and (.Values.persistence.logs.enabled) (not .Values.persistence.logs.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-logs" (include "server.name" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  storageClassName: "{{ default "" .Values.persistence.logs.storageClass .Values.global.storageClass }}"
  accessModes:
  {{- range .Values.persistence.logs.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
{{- end }}
